# This workflow is licensed under the Apache License, Version 2.0
# Copyright (c) Abstract Machines

name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                component: ['users','things' , 'coap', 'http', 'mqtt','ws', 'certs', 'cli', 'lora', 'opcua']

                include: 
                  - component: 'users'
                    paths: 'users/** cmd/users/**'
                    docker_image: 'docker_users'
        
                  - component: 'things'
                    paths: 'things/** cmd/things/**'
                    docker_image: 'docker_things'
        
                  - name: 'coap'
                    paths: 'coap/** cmd/coap/**'
                    docker_image: 'docker_coap'
        
                  - name: 'http'
                    paths: 'http/** cmd/http/**'
        
                  - name: 'mqtt'
                    paths: 'mqtt/** cmd/mqtt/**'
        
                  - name: 'certs'
                    paths:  'certs/** cmd/certs/**'
        
                  - name: 'ws'
                    paths: 'ws/** cmd/ws/** things/api/grpc/** auth/service.go auth/api/grpc/client.go'
        
                  - name: 'cli'
                    paths: 'cli/** cmd/cli/**'
        
                  - name: 'lora'
                    paths: 'lora/** cmd/lora/**'
        
                  - name: 'opcua'
                    paths: 'opcua/** cmd/opcua/** things/api/grpc/** auth/service.go auth/api/grpc/client.go' 
        
        name: build ${{ matrix.component }}

        steps:
          - name: Checkout Code
            uses: actions/checkout@v2

        
          - name : Setup Go
            uses: actions/setup-go@v4
            with:
                go-version: 1.21.x

          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Publish Docker Image
            uses: elgohr/Publish-Docker-Github-Action@v5
            with: 
                name: magistrala/${{ matrix.component }}
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
                dockerfile: docker/Dockerfile


    build-provision:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout
            uses: actions/checkout@v2
    
          - name: Check for changes in specific paths
            uses: dorny/paths-filter@v2
            id: changes
            with:
                filters: |
                    any:
                        - 'provision/**'
                        - 'cmd/provision/**'
                        - 'things/api/grpc/**'
                        - 'auth/service.go'
                        - 'auth/api/grpc/client.go'
    
          - name: Setup Go
            uses: actions/setup-go@v2
            with:
                go-version: 1.21
    
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
    
          - name: Push Provision
            uses: elgohr/Publish-Docker-Github-Action@v5
            with: 
                name: magistrala/http:latest
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
                dockerfile: docker/Dockerfile
