# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

name: golangci-lint
on:
  push:
    branches:
      - main
      - MG-35-self-hostrunner

  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
